name: hop_pos
description: Health Outreach POS.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  window_manager: ^0.3.7
  package_info_plus: ^4.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  internet_connection_checker: ^1.0.0+1
  logger: ^2.0.2+1
  loading_indicator: ^3.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  drift_db_viewer: ^2.0.0
  shimmer: ^3.0.0
  flutter_typeahead: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.0
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
